version: "3.8"

services:
  # Backend Node.js
  app:
    build: .
    # Port machine:port conteneur
    ports:
      - "5001:5000"  # sur la machine localhost:5001
    environment:
      - MONGO_URI=mongodb://mongo:27017/KenzDB
      - PORT=5000       # port interne du conteneur
    depends_on:
      - mongo
    restart: unless-stopped

  # MongoDB
  mongo:
    image: mongo:6
    restart: unless-stopped
    ports:
      - "27017:27017"  # accessible depuis localhost:27017
    environment:
      MONGO_INITDB_DATABASE: KenzDB
    volumes:
      - mongo_data:/data/db

# Volume pour persistance des donn√©es MongoDB
volumes:
  mongo_data:
